name: assignment4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log Start Time
        run: echo "$(date -Iminutes)" > /tmp/log.txt

      - name: Create .env file
        run: echo "NINJA_API_KEY=${{secrets.NINJA_API_KEY}}" > .env

      - name: Log Submitter
        run: echo "Alexander Gorelik" >> /tmp/log.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build stocks service image
        id: build_stocks
        uses: docker/build-push-action@v4
        with:
          context: .
          file: stocks/Dockerfile
          tags: stocks:latest
          outputs: type=docker, dest=/tmp/stocks_image.tar

      - name: Build capital-gains service image
        id: build_capital_gains
        uses: docker/build-push-action@v4
        with:
          context: .
          file: capital-gains/Dockerfile
          tags: capital-gains:latest
          outputs: type=docker, dest=/tmp/capital-gains_image.tar

      - name: Check Build Success
        if: always()
        run: |
          if [ "${{ steps.build_stocks.outcome }}" == "success" ] && [ "${{ steps.build_capital_gains.outcome }}" == "success" ]; then
            echo "image successfully built" >> /tmp/log.txt
          else
            echo "image not able to be built" >> /tmp/log.txt
          fi

      - name: Upload stocks artifact
        uses: actions/upload-artifact@v4
        with:
          name: stocks-image
          path: /tmp/stocks_image.tar

      - name: Upload capital-gains artifact
        uses: actions/upload-artifact@v4
        with:
          name: capital-gains-image
          path: /tmp/capital-gains_image.tar

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: /tmp/log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download log artifact
        uses: actions/download-artifact@v4
        with:
          name: log
          path: /tmp

      - name: Download stocks artifact
        uses: actions/download-artifact@v4
        with:
          name: stocks-image
          path: /tmp

      - name: Download capital-gains artifact
        uses: actions/download-artifact@v4
        with:
          name: capital-gains-image
          path: /tmp

      - name: Load Stocks service image
        run: docker load --input /tmp/stocks_image.tar

      - name: Load Capital Gains service image
        run: docker load --input /tmp/capital-gains_image.tar

      - name: Create .env file
        run: echo "NINJA_API_KEY=${{secrets.NINJA_API_KEY}}" > .env

      - name: Run Containers
        run: docker compose up -d

      - name: Update log for container status
        run: docker ps | grep -q stocks && docker ps | grep -q capital-gains && echo "Container up and running" >> /tmp/log.txt || echo "Container failed to run" >> /tmp/log.txt

      - name: Wait for container to initialize
        run: sleep 5

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests

      - name: Test with pytest
        run: pytest -v tests/assn4_tests.py > /tmp/assn4_test_results.txt

      - name: Ensure Test Results File Exists
        if: always()
        run: touch /tmp/assn4_test_results.txt

      - name: Update Log for Test Results
        if: always()
        run: |
          if grep -q "failed" /tmp/assn4_test_results.txt; then
            echo "tests failed" >> /tmp/log.txt
          else
            echo "tests succeeded" >> /tmp/log.txt
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /tmp/assn4_test_results.txt

      - name: Upload Updated Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: /tmp/log.txt
          overwrite: true


