name: assignment4

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Export Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log Start Time
        run: echo "$(date -Iminutes)" > /tmp/log.txt

      - name: Create .env file
        run: echo "NINJA_API_KEY=${{secrets.NINJA_API_KEY}}" > .env

      - name: Log Submitter
        run: echo "Alexander Gorelik" >> /tmp/log.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build stocks service image
        id: build_stocks
        uses: docker/build-push-action@v4
        with:
          context: .
          file: stocks/Dockerfile
          tags: stocks:latest
          outputs: type=docker, dest=/tmp/stocks_image.tar

      - name: Build capital-gains service image
        id: build_capital_gains
        uses: docker/build-push-action@v4
        with:
          context: .
          file: capital-gains/Dockerfile
          tags: capital-gains:latest
          outputs: type=docker, dest=/tmp/capital-gains_image.tar

      - name: Check Build Success
        if: always()
        run: |
          if [ "${{ steps.build_stocks.outcome }}" == "success" ] && [ "${{ steps.build_capital_gains.outcome }}" == "success" ]; then
            echo "image successfully built" >> /tmp/log.txt
          else
            echo "image not able to be built" >> /tmp/log.txt
          fi

      - name: Upload stocks artifact
        uses: actions/upload-artifact@v4
        with:
          name: stocks-image
          path: /tmp/stocks_image.tar

      - name: Upload capital-gains artifact
        uses: actions/upload-artifact@v4
        with:
          name: capital-gains-image
          path: /tmp/capital-gains_image.tar

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log.txt
          path: /tmp/log.txt


